title: BioEfficiency Lab
description: >-
  The BioEfficiency Lab at TU Delft studies quantitative metabolism,
  bioenergetics and bioengineering across biological scales.
url: "mvieiralara.github.io"
baseurl: ""

markdown: kramdown
permalink: pretty
timezone: Europe/Amsterdam

author:
  name: Marcel Vieira-Lara
  email: M.A.VieiraLara@tudelft.nl

social:
  scholar: "https://scholar.google.com/citations?hl=en&user=kvnKhYoAAAAJ&view_op=list_works&sortby=pubdate"
  linkedin: https://www.linkedin.com/in/mavl
  orcid: https://orcid.org/0000-0003-3115-3520

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
