title: BioEfficiency Lab
description: >-
  The BioEfficiency Lab at TU Delft studies quantitative metabolism,
  bioenergetics and bioengineering across biological scales.
url: "mvieiralara.github.io"
baseurl: ""

markdown: kramdown
permalink: pretty
timezone: Europe/Amsterdam

author:
  name: Marcel Vieira-Lara
  email: M.A.VieiraLara@tudelft.nl

social:
  scholar: https://scholar.google.com/citations?hl=en&user=kvnKhYoAAAAJ
  linkedin: https://www.linkedin.com/in/marcel-vieira-lara

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
